// Writes the offline app files into build/: manifest, icons, service worker
// and the list of Scratch library assets to store on the device.
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import {spawnSync} from 'child_process';
import {fileURLToPath} from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const buildDir = path.join(root, 'build');
const guiPath = path.join(buildDir, 'gui.js');

if (!fs.existsSync(guiPath)) {
    console.error('build/gui.js não existe. Rode npm run build antes.');
    process.exit(1);
}

const cacheName = `aluno-maker-${crypto.createHash('sha1')
    .update(String(fs.statSync(guiPath).mtimeMs))
    .update(String(fs.statSync(guiPath).size))
    .digest('hex')
    .slice(0, 10)}`;

const iconsDir = path.join(buildDir, 'icons');
fs.mkdirSync(iconsDir, {recursive: true});
const iconScript = spawnSync('python3', ['-'], {
    input: `
from PIL import Image
from pathlib import Path
logo = Image.open(${JSON.stringify(path.join(root, 'src/components/menu-bar/aluno-maker-logo.png'))}).convert('RGBA')
out = Path(${JSON.stringify(iconsDir)})
purple = (76, 29, 149, 255)
for size in (192, 512):
    canvas = Image.new('RGBA', (size, size), purple)
    pad = int(size * 0.12)
    box = size - pad * 2
    scale = min(box / logo.width, box / logo.height)
    resized = logo.resize((max(1, int(logo.width * scale)), max(1, int(logo.height * scale))), Image.Resampling.LANCZOS)
    canvas.alpha_composite(resized, ((size - resized.width) // 2, (size - resized.height) // 2))
    canvas.save(out / f'icon-{size}.png')
`,
    encoding: 'utf8'
});
if (iconScript.status !== 0) {
    console.error(iconScript.stderr || iconScript.stdout);
    process.exit(iconScript.status || 1);
}

const skipFile = name => name.endsWith('.map') ||
    name.endsWith('.LICENSE.txt') ||
    name === '.DS_Store' ||
    name === 'sw.js' ||
    name === 'offline-assets.json';

const walk = (dir, base = '') => {
    const found = [];
    for (const entry of fs.readdirSync(dir, {withFileTypes: true})) {
        if (entry.name.startsWith('.')) continue;
        const rel = base ? `${base}/${entry.name}` : entry.name;
        if (entry.isDirectory()) found.push(...walk(path.join(dir, entry.name), rel));
        else if (!skipFile(entry.name)) found.push(rel);
    }
    return found;
};

const shell = walk(buildDir).map(rel => (rel === 'gui.js' ? `gui.js?v=${cacheName}` : rel));

const assetIds = new Set();
const collect = value => {
    if (!value || typeof value !== 'object') return;
    if (typeof value.md5ext === 'string') assetIds.add(value.md5ext);
    for (const child of Object.values(value)) collect(child);
};
for (const name of ['sprites.json', 'costumes.json', 'backdrops.json', 'sounds.json']) {
    collect(JSON.parse(fs.readFileSync(path.join(root, 'src/lib/libraries', name), 'utf8')));
}
const offlineAssets = [];
for (const id of assetIds) {
    offlineAssets.push(`https://assets.scratch.mit.edu/internalapi/asset/${id}/get/`);
    offlineAssets.push(`https://cdn.assets.scratch.mit.edu/internalapi/asset/${id}/get/`);
}
fs.writeFileSync(path.join(buildDir, 'offline-assets.json'), JSON.stringify(offlineAssets));
shell.push('offline-assets.json');

const manifest = {
    name: 'Aluno Maker',
    short_name: 'Aluno Maker',
    lang: 'pt-BR',
    start_url: './',
    scope: './',
    display: 'standalone',
    background_color: '#4c1d95',
    theme_color: '#4c1d95',
    icons: [
        {src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any'},
        {src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any'},
        {src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable'}
    ]
};
fs.writeFileSync(path.join(buildDir, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
shell.push('manifest.json');

const sw = `/* Generated by scripts/build-pwa.mjs. Cache ${cacheName}. */
const CACHE = ${JSON.stringify(cacheName)};
const SHELL = ${JSON.stringify(shell.map(item => `./${item}`))};

self.addEventListener('install', event => {
    event.waitUntil((async () => {
        const cache = await caches.open(CACHE);
        for (const url of SHELL) {
            try {
                await cache.add(new Request(url, {cache: 'reload'}));
            } catch (error) {
                if (url.indexOf('gui.js') !== -1 || url.indexOf('index.html') !== -1) throw error;
            }
        }
        await self.skipWaiting();
    })());
});

self.addEventListener('activate', event => {
    event.waitUntil((async () => {
        const keys = await caches.keys();
        await Promise.all(keys.filter(key => key !== CACHE).map(key => caches.delete(key)));
        await self.clients.claim();
    })());
});

const cacheFirst = async request => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(request);
    if (cached) return cached;
    const fresh = await fetch(request);
    if (fresh && fresh.ok) {
        await cache.put(request, fresh.clone());
    }
    return fresh;
};

self.addEventListener('fetch', event => {
    const request = event.request;
    if (request.method !== 'GET') return;
    const url = new URL(request.url);
    const sameOrigin = url.origin === self.location.origin;
    const scratchAsset = url.hostname === 'assets.scratch.mit.edu' ||
        url.hostname === 'cdn.assets.scratch.mit.edu';
    if (request.mode === 'navigate') {
        event.respondWith((async () => {
            const path = url.pathname;
            const downloadPage = path === '/baixar' || path === '/baixar/' || path === '/baixar/index.html';
            try {
                const fresh = await fetch(request);
                const cache = await caches.open(CACHE);
                if (downloadPage) await cache.put('./baixar/index.html', fresh.clone());
                else if (path === '/' || path === '/index.html') await cache.put('./index.html', fresh.clone());
                return fresh;
            } catch (error) {
                if (downloadPage) return (await caches.match('./baixar/index.html')) || Response.error();
                return (await caches.match('./index.html')) || Response.error();
            }
        })());
        return;
    }
    if (!sameOrigin && !scratchAsset) return;
    event.respondWith(cacheFirst(request));
});
`;
fs.writeFileSync(path.join(buildDir, 'sw.js'), sw);

for (const htmlName of ['index.html', 'player.html', 'blocks-only.html', 'compatibility-testing.html']) {
    const htmlPath = path.join(buildDir, htmlName);
    if (!fs.existsSync(htmlPath)) continue;
    const html = fs.readFileSync(htmlPath, 'utf8')
        .replace(/src="(gui|player|blocksonly|compatibilitytesting)\.js(?:\?[^"]*)?"/g, `src="$1.js?v=${cacheName}"`);
    fs.writeFileSync(htmlPath, html);
}

console.log(`PWA ${cacheName}: ${shell.length} arquivos do app, ${offlineAssets.length} assets das bibliotecas`);
